# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-01 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0026_game_show_times'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screenshot',
            name='img',
            field=models.ImageField(null=True, upload_to=b'/media'),
        ),
    ]
