# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-03 21:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0030_auto_20160201_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='img',
            field=models.ImageField(null=True, upload_to=b'team/'),
        ),
    ]
