"""
Django settings for webapp project.

Generated by 'django-admin startproject' using Django 1.8.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
import random
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'ei011fy^w3*cipgpxbw5=3xzg759bg$y0$7!zpb^+yca_s33xj'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = (
    
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
                'bootstrap3',
                'polls',
                #'social_auth',
                'social.apps.django_app.default',
                
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'webapp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'webapp.wsgi.application'


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'webappdb',
        'USER': 'root',
        'PASSWORD': 'qwerty7gas',
}
}

LANGUAGE_CODE = 'ru-RU'
TIME_ZONE = 'UTC'

USE_I18N = True
AUTH_USER_MODEL = 'polls.MyUser'


STATIC_URL = '/static/'
STATIC_ROOT = "/home/myuser/webapp/webapp/static/"
MEDIA_URL = '/media/'
MEDIA_ROOT = "/home/myuser/webapp/webapp/media/"

ADMIN_MEDIA_PREFIX = '/static/admin/'
STATICFILES_FINDERS = (
                       
                       'django.contrib.staticfiles.finders.FileSystemFinder',
                       
                       'django.contrib.staticfiles.finders.AppDirectoriesFinder',
                       
                       )
TEMPLATE_DIRS = (
                 "/Users/erik/Movies/webapp/polls/templates",
                 )

SOCIAL_AUTH_VK_OAUTH2_KEY = '5286780'
SOCIAL_AUTH_VK_OAUTH2_SECRET = 'k6piL98lxkLhmwInHYUj'

#SOCIAL_AUTH_USER_MODEL = 'polls.models.MyUser'
SOCIAL_AUTH_URL_NAMESPACE = 'social'

SOCIAL_AUTH_LOGIN_REDIRECT_URL = '127.0.0.1'
SOCIAL_AUTH_LOGIN_URL = '127.0.0.1/social_login/'
SOCIAL_AUTH_NEW_USER_REDIRECT_URL = '127.0.0.1/posts/'

#SOCIAL_AUTH_USERNAME_IS_FULL_EMAIL = True

SOCIAL_AUTH_STRATEGY = 'social.strategies.django_strategy.DjangoStrategy'
SOCIAL_AUTH_STORAGE = 'social.apps.django_app.default.models.DjangoStorage'
SOCIAL_AUTH_SANITIZE_REDIRECTS = False

SOCIAL_AUTH_PIPELINE = (
    'social.pipeline.social_auth.social_details',
    'social.pipeline.social_auth.social_uid',
    'social.pipeline.social_auth.auth_allowed',
    # 'social.pipeline.social_auth.social_user',
    'social.pipeline.user.get_username',
    #'example.app.pipeline.require_email',
    #'social.pipeline.social_auth.associate_by_email',
    # 'polls.views.login_vk',
    # 'social.pipeline.mail.mail_validation',
    'social.pipeline.user.create_user',
    'social.pipeline.social_auth.associate_user',
    'social.pipeline.debug.debug',
    'social.pipeline.social_auth.load_extra_data',
    'social.pipeline.user.user_details',
    'social.pipeline.debug.debug'
)


AUTHENTICATION_BACKENDS = (
    'social.backends.vk.VKOAuth2',  
    'social.apps.django_app.context_processors.backends',
    'social.apps.django_app.context_processors.login_redirect',
    'django.contrib.auth.backends.ModelBackend',
)


EMAIL_HOST_USER = 'ericovva@gmail.com'
#DEFAULT_FROM_EMAIL = 'user@gmail.com'
EMAIL_HOST_PASSWORD = 'SwiftSoul7143'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
#EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'